### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by jonuts** [m2osw/libtld#1]
Getting errors when `cmake`-ing latest `libtld` with latest `snapcmakemodules` on ubuntu 14.04:

```
~/BUILD$ cmake -DCMAKE_MODULE_PATH=../snapcmakemodules/Modules -DSnapCMakeModules_DIR:PATH=../snapcmakemodules/Modules -DSnapDoxygen_DIR:PATH=../snapcmakemodules/Modules ../libtld
-- Boost version: 1.54.0
CMake Error at /home/user/snapcmakemodules/Modules/SnapCMakeModulesConfig.cmake:115 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  CMakeLists.txt:49 (SnapGetVersion)


CMake Error at src/CMakeLists.txt:79 (set_target_properties):
  set_target_properties called with incorrect number of arguments.


CMake Error at doc/CMakeLists.txt:43 (AddDoxygenTarget):
  AddDoxygenTarget Function invoked with incorrect arguments for function
  named: AddDoxygenTarget


Warning: The pkg tool was not found. In order to package libtld with wpkg, you want to install wpkg on your system and eventually define the environment variable named WPKG_DIST_PATH to point where it was installed.
-- Configuring incomplete, errors occurred!
See also "/home/user/BUILD/CMakeFiles/CMakeOutput.log".
```

Any idea what's going on?

**Comment by dooglio** [comment]
As far as I can tell, that should work. Do you have the `devscripts` package installed? What version of CMake are you running?

**Comment by AlexisWilke** [comment]
It could be that 14.04 is not supported properly anymore. We may be using a newer feature of cmake not available in 14.04.

**Comment by dooglio** [comment]
We specify a minimum of CMake `v2.8.4` here:
https://github.com/m2osw/libtld/blob/df0d0a67642a207a3a9d3a33d174f5f95b45c6a8/CMakeLists.txt#L29

Maybe that's not good enough any more? We might need `v3.x+`.

**Comment by dooglio** [comment]
@jonuts would you try upgrading CMake to at least `3.5.X`?

**Comment by jonuts** [comment]
Installed cmake `3.11.1` and the devscripts package. Same result.

**Comment by dooglio** [comment]
@jonuts you need to have `dpkg-dev` installed. Then you can run `cmake`. I will put in a patch which gives you a better warning in `snapcmakemodules`.

**Comment by dooglio** [comment]
Under Ubuntu 17.10, there is a package called `ubuntu-dev-tools` which installs everything you need to build debian packages. I don't know if it exists on Ubuntu 14.X.

**Comment by jonuts** [comment]
`ubuntu-dev-tools` is in the 14.10 repos also. Installed but still no dice

**Comment by dooglio** [comment]
What about `dpkg-dev`? Is it installed? Specifically, you need the `dpkg-parsechangelog` command to be in your path.

**Comment by jonuts** [comment]
Yes to both

**Comment by dooglio** [comment]
If you type `dpkg-parsechangelog` into your shell, does it give you an error or does it find the command?

**Comment by jonuts** [comment]
@dooglio it's in my path and the command runs but it gives an error `tail: cannot open ‘debian/changelog’ for reading: No such file or directory`

**Comment by dooglio** [comment]
Does `debian/changelog` appear in your `../libtld` directory? AKA the root of the source?

**Comment by AlexisWilke** [comment]
@jonuts If you'd like to bypass that error, you can forcibly set the LIBTLD_VERSION_MAJOR and LIBTLD_VERSION_MINOR variables. You can also set LIBTLD_VERSION_PATCH. Just use the library version you downloaded. Right now it's 1.5.9 so something like this would work:

    define(LIBTLD_VERSION_MAJOR 1)
    define(LIBTLD_VERSION_MINOR 5)
    define(LIBTLD_VERSION_PATCH 9)

We use the `dpkg-parsechangelog` tool to extract those numbers from the `debian/changelog` file automatically (as  to avoid data duplication).

**Comment by AlexisWilke** [comment]
Also, there is another `libtld-only-CMakeLists.txt` file under the `dev` folder which skips on that version gathering and may work better for you. To test with that one do:

    cp dev/libtld-only-CMakeLists.txt CMakeLists.txt

You may want to make a backup copy of the main CMakeLists.txt first.

**Comment by jonuts** [comment]
@AlexisWilke where should I use the `define()` statements?

Changing to `libtld-only-CMakeLists.txt` gives this error now:

```
CMake Error at CMakeLists.txt:77 (add_library):
  Cannot find source file:

    src/tld_data.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:77 (add_library):
  No SOURCES given to target: tld_static


CMake Error at CMakeLists.txt:50 (add_library):
  No SOURCES given to target: tld
```

**Comment by AlexisWilke** [comment]
Ah. I'll have to think about this. The tld_data.c is expected to be generated when you try to compile from the source. There is a copy (remove the .txt extension) I guess we should have a copy in the git repository as well. It doesn't change often but the _normal_ version should not be in the git or it may not get generated properly...

[tld_data.c.txt](https://github.com/m2osw/libtld/files/1959189/tld_data.c.txt)

**Comment by dooglio** [comment]
@AlexisWilke is this still an issue?

**Comment by AlexisWilke** [comment]
I was thinking that all the contrib projects should compile on their own. Without the dependency on the Snap! C++ specific cmake project. Of course, some of the contrib projects depend on others (i.e. the `advgetopt` is reused by `iplock`, for example.) I think that's fine. However, the `libtld` would work without it.

So... in the old days, I would create a .tar.gz file with the _extra_ CMakeLists.txt and the pre-generated `tld_data.c` file. That source could be compiled easily. You added the dependency on the Snap cmake project making it "difficult" to compile libtld on its own... That is, pretty much no one understands how that works.

Now like `zipios` and `libuv1-snap` and `log4cplus` can be compiled independently.

I think that whatever we use from the `.../cmake/Modules` can be copied in a `cmake` sub-folder within `libtld`. That means we have some duplicated files. But it would make it easier for our libtld-only users.

**Comment by dooglio** [comment]
So leave this open? Or should I close this and you can create a separate issue for it?

**Comment by AlexisWilke** [comment]
I think this issue is fine as it is. Plus it explains how to get things to compile for others who run in the same problem. You could tweak the _title_, though.
