### ISSUE TITLE
qt5 compiler werror flag 

### ISSUE THREAD

**Issue by DRTEK** [m2osw/libtld#5]
Hello thank you for the new release , 
currently I am using  Qt version 5.14.2 and when i tried to compile cmake gave the error below 
make: Entering directory '/root/libtld/build'
make[1]: Entering directory '/root/libtld/build'
make[2]: Entering directory '/root/libtld/build'
make[2]: Leaving directory '/root/libtld/build'
make[2]: Entering directory '/root/libtld/build'
[  2%] Building CXX object src/CMakeFiles/tld_parser.dir/tld_parser.cpp.o
/root/libtld/src/tld_parser.cpp: In function ‘QString snap::tld_encode(const QString&, int&)’:
/root/libtld/src/tld_parser.cpp:165:24: error: ‘void QList<T>::swap(int, int) [with T = QString]’ is deprecated: Use QList<T>::swapItemsAt() [-Werror=deprecated-declarations]
  165 |         split.swap(i, j);
      |                        ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QMap:1,
                 from /root/libtld/src/tld_parser.cpp:35:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:225:10: note: declared here
  225 |     void swap(int i, int j) { swapItemsAt(i, j); }
      |          ^~~~
i changed the deprecated swap with swapItemsAt and it compiled fine 

you might want to know that 

thank you for your efforts in this very helpful library

**Comment by AlexisWilke** [comment]
Okay, thank you for letting me know. I added a compile time test of the QT version to select which version to use. Only that this time I can't be sure it will properly switch to the new function.

Are you compiling under Linux or MS-Windows? If Linux, which flavor? version?

**Comment by DRTEK** [comment]
sorry for the delay 
the info you requested is below 
  Operating System: Ubuntu 20.10
            Kernel: Linux 5.8.0-48-generic
      Architecture: x86-64

**Comment by AlexisWilke** [comment]
Okay, I got 21.04 going in a VPS and I see Qt5 errors about a deprecated flag now. That should be easy enough to fix.

**Comment by AlexisWilke** [comment]
There is another change I pushed, you should be able to compile now. I tested with 21.04 and there was another deprecated call with the `QString::split()` function. The whole library (and dependencies) compiled on 21.04.
